# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Multiply an number by 4
#'
#' @param x a single integer
#'
#'@export
eda_rcpp <- function(x) {
    .Call('_edar_eda_rcpp', PACKAGE = 'edar', x)
}

